package sample;

@SuppressWarnings("all")
public class Foo {

    @Generated(ABSTRACT)
    @Override
    public String foo() {

        return ExceptionUtils.subclassResponsibility();
    }

    @Generated(ABSTRACT)
    @Override
    public String bar() {

        return "";
    }

    @Generated({ABSTRACT, REPOSITORY_STUB, SUBSET_STUB})
    @Override
    public Color baz() {
        /* Abstract method created by ... */

        /* Subset stub generated by ... */

        throw new SmtException("SMT error");
    }


    @Generated({ABSTRACT, REPOSITORY_STUB, SUBSET_STUB})
    @Override
    public Color doo() {
        return null;
    }

    public String beez() {
        return ExceptionUtils.subclassResponsibility();
    }

    @Generated(ABSTRACT)
    public String booz() {
        throw new DoesNotUnderstandException();
    }

}
